# Generated by Django 5.2.2 on 2025-06-04 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('father_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('artist', models.CharField(default='Лабытнанги', max_length=200, verbose_name='Исполнитель')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('cover', models.ImageField(upload_to='music/albums/', verbose_name='Обложка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Музыкальный альбом',
                'verbose_name_plural': 'Музыкальные альбомы',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='PoetryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('year', models.IntegerField(verbose_name='Год издания')),
                ('author', models.CharField(default='Лабытнанги', max_length=100, verbose_name='Автор')),
                ('cover', models.ImageField(upload_to='covers/', verbose_name='Обложка')),
                ('pdf_file', models.FileField(upload_to='books/', verbose_name='PDF файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Книга стихов',
                'verbose_name_plural': 'Книги стихов',
                'ordering': ['year'],
            },
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AlterModelOptions(
            name='poem',
            options={'ordering': ['order'], 'verbose_name': 'Стихотворение', 'verbose_name_plural': 'Стихотворения'},
        ),
        migrations.RemoveField(
            model_name='poem',
            name='year',
        ),
        migrations.AddField(
            model_name='poem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='content',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='poem',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='father_app.poetrybook'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер')),
                ('audio_file', models.FileField(upload_to='music/tracks/', verbose_name='Аудиофайл')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Длительность')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='father_app.musicalbum')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
