# Generated by Django 5.2.2 on 2025-06-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('father_app', '0003_alter_poetrybook_options_alter_musicalbum_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalbum',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text='Месяц выпуска альбома (1-12)', null=True, verbose_name='Месяц публикации'),
        ),
    ]
