# Generated by Django 5.2.2 on 2025-06-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('father_app', '0004_musicalbum_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicalbum',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Музыкальный альбом', 'verbose_name_plural': 'Музыкальные альбомы'},
        ),
    ]
